### ISSUE TITLE
2 sections for updating Redhat libs.

### ISSUE THREAD

**Issue by charliedarsey** [ChristopherDavenport/ansible-role-oracle-client#8]
the first installs from centos repos, the other from Redhat repos. I'm new to ansible, but that didn't seem right.

- name: Download compat-libstdc++ libs if EL
  get_url:
    url: ftp://195.220.108.108/linux/centos/7.3.1611/os/x86_64/Packages/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm
    dest: "{{ oracle_client_tmp_install_storage }}/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm"
    owner: "{{ __oracle_client_user }}"
    group: "{{ __oracle_client_group }}"
  when:
    - ansible_os_family == "RedHat"
    - not __oracle_client_installed

- name: Install compat-libstdc++ libs if EL
  yum:
    name: "{{ oracle_client_tmp_install_storage }}/compat-libstdc++-33-3.2.3-72.el7.x86_64.rpm"
    state: present
  when:
    - ansible_os_family == "RedHat"
    - not __oracle_client_installed

**Comment by ChristopherDavenport** [comment]
The first downloads the file, then the second installs it from the now locally present RPM file.

Is that the answer were you looking for or were you proposing a new feature?

**Comment by charliedarsey** [comment]
Yes, I get it now. Thanks for the reply.

**Comment by ChristopherDavenport** [comment]
Glad to help.
